source 'http://rubygems.org'

gem 'rails', '3.2.22'
gem 'rubyzip'
gem 'will_paginate'
gem 'mysql2', '~> 0.3.21'
gem 'devise'
gem 'devise_ldap_authenticatable'
gem 'devise-encryptable'
gem 'marked-rails'
gem 'delayed_job_active_record'
gem 'passenger'
gem 'pg'
