#!/bin/sh

# Sorry...

VBOX_PORT="${VBOX_PORT:-22}"
SSH="ssh -l '$VBOX_USER' -p '$VBOX_PORT' '$VBOX_HOST'"

MEMORY_FREE=$(eval "$SSH free -m" | awk 'NR==2{print $7}')
DISK_FREE=$(eval "$SSH df -m ~$VBOX_USER" | awk 'NR==2{print $4}')

if [ "$MEMORY_FREE" -lt "10240" ] || [ "$DISK_FREE" -lt "30720" ]
then
	echo "Resource exhaustion warning" >&2
	exit 1
fi
